# Generated by Django 5.1.7 on 2026-03-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_pendingevent_event_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, default='manual', help_text='Source of this event record: manual, scraped, custom_scrape, etc.', max_length=100),
        ),
    ]
