# Generated by Django 5.1.7 on 2026-03-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_event_approval_metadata'),
    ]

    operations = [
    ]
