# Generated by Django 5.1.7 on 2026-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_merge_0003_event_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_hybrid',
            field=models.BooleanField(default=False, verbose_name='Is Hybrid'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is Online'),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('fr', 'French'), ('en', 'English'), ('other', 'Other')], default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='event',
            name='notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Notification Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, null=True, verbose_name='Registration Link'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Source Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Source URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='Tags'),
        ),
    ]
