# Generated by Django 5.1.15 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_domain_model_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="entities",
            field=models.JSONField(blank=True, default=dict, verbose_name="Entities"),
        ),
    ]
