# Generated by Django 5.1.15 on 2026-03-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_approval_date_event_approved_by_and_more'),
        ('events', '0006_domain_model_indexes'),
    ]

    operations = [
    ]
