# Generated by Django 5.1.7 on 2026-03-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_merge_20260326_2135'),
        ('events', '0011_merge'),
    ]

    operations = [
    ]
