# Generated by Django 5.1.15 on 2026-04-11 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_merge_0007_merge_20260326_2135_0011_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='event',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_events', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By'),
        ),
        migrations.AddField(
            model_name='event',
            name='rejection_note',
            field=models.TextField(blank=True, default='', verbose_name='Rejection Note'),
        ),
    ]
