# Generated by Django 5.1.15 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_merge_0007_merge_20260326_2135_0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Scraped At'),
        ),
        migrations.AddField(
            model_name='event',
            name='update_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Update Count'),
        ),
    ]