# Generated by Django 5.1.15 on 2026-04-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_is_past_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Registration Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, db_index=True, max_length=500, verbose_name='Website'),
        ),
    ]
