target-version = "py311"
line-length = 88

include = [
    "Plateforme/**/*.py",
    "fastapi_chatbot/**/*.py"
]

exclude = [
    ".venv",
    "**/site-packages/**",
    "**/migrations/**",
    "**/__pycache__/**",
    "grafana",
    "prometheus",
    "nginx",
    "monitoring",
    "elasticsearch",
    "ingest_logs",
    "reports"
]

[lint]
select = ["E", "W", "F", "B", "I", "N", "UP", "SIM"]
ignore = ["E501", "B008"]

[lint.per-file-ignores]
"Plateforme/manage.py" = ["ALL"]
"Plateforme/**/migrations/*.py" = ["ALL"]
"Plateforme/**/settings*.py" = ["F401", "F811"]