# Generated by Django 5.1.7 on 2026-02-26 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Source Name')),
                ('category', models.CharField(choices=[('events', 'Events'), ('tools', 'Tools'), ('news', 'News'), ('courses', 'Courses'), ('institutions', 'Institutions')], max_length=50, verbose_name='Category')),
                ('base_url', models.URLField(blank=True, verbose_name='Base URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Last Scraped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scraping Source',
                'verbose_name_plural': 'Scraping Sources',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='Status')),
                ('items_found', models.PositiveIntegerField(default=0, verbose_name='Items Found')),
                ('items_created', models.PositiveIntegerField(default=0, verbose_name='Items Created')),
                ('items_skipped', models.PositiveIntegerField(default=0, verbose_name='Items Skipped')),
                ('errors', models.TextField(blank=True, verbose_name='Errors')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Triggered By')),
            ],
            options={
                'verbose_name': 'Scraping Run',
                'verbose_name_plural': 'Scraping Runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
