# Generated by Django 5.1.7 on 2026-03-05 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_scrapingrun_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSourceHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('source_name', models.CharField(help_text="Logical name of the source (e.g. 'WikiCFP', 'HuggingFace Hub').", max_length=200, verbose_name='Source Name')),
                ('base_url', models.URLField(blank=True, verbose_name='Base URL')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='Total Attempts')),
                ('total_successes', models.PositiveIntegerField(default=0, verbose_name='Total Successes')),
                ('total_failures', models.PositiveIntegerField(default=0, verbose_name='Total Failures')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='Consecutive Failures')),
                ('health_score', models.FloatField(default=100.0, help_text='0-100. Decays on failure, recovers on success.', verbose_name='Health Score')),
                ('circuit_state', models.CharField(choices=[('closed', 'Closed (healthy)'), ('open', 'Open (tripped)'), ('half_open', 'Half-Open (probing)')], default='closed', max_length=12, verbose_name='Circuit State')),
                ('circuit_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Circuit Opened At')),
                ('circuit_cooldown_seconds', models.PositiveIntegerField(default=300, help_text='Seconds before an open circuit moves to half-open.', verbose_name='Cooldown (s)')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Attempt')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Success')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Failure')),
                ('avg_response_time', models.FloatField(blank=True, null=True, verbose_name='Avg Response Time (s)')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
            ],
            options={
                'verbose_name': 'Source Health',
                'verbose_name_plural': 'Source Health Records',
                'ordering': ['category', 'source_name'],
                'unique_together': {('category', 'source_name')},
            },
        ),
    ]
