# Generated by Django 5.1.7 on 2026-03-05 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_add_scraping_source_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItemMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('item_title', models.CharField(max_length=300, verbose_name='Item Title')),
                ('item_id', models.CharField(blank=True, default='', help_text='UUID of the scraped item in its source table.', max_length=50, verbose_name='Item UUID')),
                ('domain_scores', models.JSONField(blank=True, default=dict, help_text='Dict of domain_key → confidence (0-1).', verbose_name='Domain Scores')),
                ('primary_domain', models.CharField(blank=True, default='general', max_length=50, verbose_name='Primary Domain')),
                ('relevance_score', models.FloatField(default=0.0, help_text='Composite score 0-100 combining recency, relevance, health, popularity.', verbose_name='Relevance Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraped Item Metadata',
                'verbose_name_plural': 'Scraped Item Metadata',
                'ordering': ['-relevance_score'],
                'indexes': [models.Index(fields=['category', 'primary_domain'], name='scraping_sc_categor_f11543_idx'), models.Index(fields=['-relevance_score'], name='scraping_sc_relevan_3d5943_idx')],
            },
        ),
    ]
