# Generated by Django 5.1.7 on 2026-03-18 17:33

from django.db import migrations, models

try:
    from pgvector.django import VectorField
except Exception:  # pragma: no cover - optional dependency in older images
    VectorField = None


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_add_scraped_item_meta'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;"),
=======
>>>>>>> b0fb41f2308c0008bb552529075f0dfda842e86e
        migrations.AddField(
            model_name='scrapeditemmeta',
            name='title_embedding',
            field=(
                VectorField(
                    blank=True,
                    dimensions=384,
                    help_text='384-dim embedding from paraphrase-multilingual-MiniLM-L12-v2.',
                    null=True,
                )
                if VectorField is not None
                else models.JSONField(
                    blank=True,
                    default=None,
                    help_text='Embedding payload for environments without pgvector.',
                    null=True,
                )
            ),
        ),
    ]
