# Generated by Django 5.1.7 on 2026-03-18 17:33

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_add_scraped_item_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditemmeta',
            name='title_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='384-dim embedding from paraphrase-multilingual-MiniLM-L12-v2.', null=True),
        ),
    ]
