# Generated by Django 5.1.7 on 2026-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_scrapeditemmeta_title_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsource',
            name='last_run_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='last_run_items_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='last_run_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='scrape_config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors or config'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='use_llm_extraction',
            field=models.BooleanField(default=True, help_text='Use LLM to extract structured data'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='use_rss',
            field=models.BooleanField(default=False, help_text='Try RSS/Atom feed detection first'),
        ),
    ]
