# Generated by Django 5.1.7 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_scrapingsource_last_run_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditemmeta',
            name='completeness_score',
            field=models.FloatField(default=0.0, help_text='Percentage of fields filled (0-100)'),
        ),
    ]
