# Generated by Django 5.1.7 on 2026-03-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_scrapeditemmeta_completeness_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingsource',
            name='last_run_status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
