# Generated by Django 5.1.7 on 2026-03-22

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0009_add_periodic_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapeditemmeta",
            name="skip_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text=_(
                    "Reason why this scraped candidate was skipped as duplicate."
                ),
                max_length=255,
                verbose_name=_("Skip Reason"),
            ),
        ),
    ]
