# Generated by Django 5.1.15 on 2026-03-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0022_adaptive_scheduler_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsource',
            name='is_default',
            field=models.BooleanField(default=False, help_text='True if this is an essential fallback source', verbose_name='Default Source'),
        ),
    ]
