# Generated by Django 5.1.15 on 2026-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0023_scrapingsource_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsource',
            name='force_playwright',
            field=models.BooleanField(default=False, help_text='Force Playwright (headless browser) for this source. Use for JavaScript-rendered pages or strict anti-bot sites.'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='proxy_url',
            field=models.CharField(blank=True, default='', help_text='Optional proxy URL for this source. Format: http://user:pass@host:port or socks5://host:port', max_length=500),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='Uncheck to disable SSL verification for this source (use for self-signed .dz university certificates)'),
        ),
    ]
