# Generated by Django 5.1.15 on 2026-04-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0026_scrapingrun_items_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingsource',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('tools', 'Tools'), ('courses', 'Courses'), ('news', 'News'), ('opportunities', 'Opportunities'), ('corpus', 'Corpus')], max_length=50, verbose_name='Category'),
        ),
    ]
