# Generated by Django 5.1.15 on 2026-04-11 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scraping', '0036_update_translation_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejecteditem',
            options={'ordering': ['-rejected_at', '-created_at'], 'verbose_name': 'Rejected Item', 'verbose_name_plural': 'Rejected Items'},
        ),
        migrations.AddField(
            model_name='rejecteditem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_rejected_items', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='rejecteditem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rejecteditem',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='rejecteditem',
            name='reason',
            field=models.CharField(choices=[('irrelevant', 'Irrelevant to Arabic NLP'), ('poor_arabic', 'Poor Arabic translation'), ('duplicate', 'Duplicate content'), ('unreliable_source', 'Unreliable source'), ('outdated', 'Outdated information'), ('low_quality', 'Low quality content'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='rejecteditem',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='rejecteditem',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rejecteditem',
            index=models.Index(fields=['category', 'rejected_at'], name='idx_rejecteditem_cat_rejected'),
        ),
    ]
