# Generated by Django 5.1.15 on 2026-04-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0037_alter_rejecteditem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingsource',
            name='force_playwright',
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='is_admin_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='last_failure_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='quarantine_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
