# Generated by Django 5.1.15 on 2026-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0042_source_mutation_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='discoveredurl',
            new_name='idx_discurl_pending_q',
            old_name='idx_discoveredurl_pending_queue',
        ),
        migrations.AlterField(
            model_name='discoveredurl',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('tools', 'Tools'), ('courses', 'Courses'), ('news', 'News'), ('opportunities', 'Opportunities'), ('corpus', 'Corpus'), ('laws', 'Laws')], db_index=True, default='events', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='rejecteditem',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('tools', 'Tools'), ('courses', 'Courses'), ('news', 'News'), ('opportunities', 'Opportunities'), ('corpus', 'Corpus'), ('laws', 'Laws')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='scrapingsource',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('tools', 'Tools'), ('courses', 'Courses'), ('news', 'News'), ('opportunities', 'Opportunities'), ('corpus', 'Corpus'), ('laws', 'Laws')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('tools', 'Tools'), ('courses', 'Courses'), ('news', 'News'), ('opportunities', 'Opportunities'), ('corpus', 'Corpus'), ('laws', 'Laws')], max_length=50, verbose_name='Category'),
        ),
    ]
