# Generated by Django 5.1.15 on 2026-04-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0043_rename_idx_discoveredurl_pending_queue_idx_discurl_pending_q_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='discoveredurl',
            new_name='idx_discurl_pending_queue',
            old_name='idx_discurl_pending_q',
        ),
    ]
