# Generated by Django 5.1.7 on 2026-03-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_chatroom', '0001_initial'),
        ('projects', '0010_alter_projectchatmessage_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchat',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectchatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
