# Generated by Django 5.1.7 on 2026-02-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context_data',
            field=models.JSONField(blank=True, help_text='Structured metadata injected when session is created for a specific item.', null=True, verbose_name='Item Context'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='context_label',
            field=models.CharField(blank=True, default='', help_text='Human-readable label shown in the chat header.', max_length=500, verbose_name='Context Label'),
        ),
    ]
