# Generated by Django 5.1.7 on 2026-02-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='pdf_filename',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='pdf_uploaded',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='document_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Filename'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='has_documents',
            field=models.BooleanField(default=False, verbose_name='Has Documents'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
