# Generated by Django 5.1.7 on 2026-02-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_context_data_chatsession_context_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='context_data',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='context_label',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='content_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content Title'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object ID'),
        ),
    ]
