# Generated by Django 5.1.7 on 2026-02-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_remove_chatsession_pdf_filename_and_more"),
        ("chatbot", "0003_remove_chatsession_context_data_and_more"),
    ]

    operations = []

