# Generated by Django 5.1.15 on 2026-04-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_merge_20260227_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
    ]
