# Generated by Django 5.1.7 on 2026-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0006_add_missing_post_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', verbose_name='Rejection Reason'),
        ),
    ]
