# Generated by Django 5.1.7 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QA", "0007_fix_post_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="arxiv_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="source_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
