<<<<<<< HEAD:Plateforme/feed/migrations/0010_alter_post_source_url.py
# Generated by Django 5.1.15 on 2026-03-26 20:58
=======
# Generated by Django 5.1.15 on 2026-03-26 20:36
>>>>>>> 98a310101d61c731410472855aff56398f807ca0:Plateforme/QA/migrations/0010_alter_post_source_url.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0009_post_authors_post_news_category_post_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, default=''),
        ),
    ]
