# Generated by Django 5.1.15 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QA", "0010_alter_post_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="entities",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
