<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-04-21 11:31
=======
# Generated by Django 5.1.15 on 2026-04-21 20:50
>>>>>>> b0fb41f2308c0008bb552529075f0dfda842e86e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0013_post_scrape_update_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='news_category',
            field=models.CharField(choices=[('paper', 'Paper'), ('news', 'Feed'), ('announcement', 'Announcement'), ('blog', 'Blog')], default='paper', max_length=20),
        ),
    ]
