# Generated by Django 5.1.15 on 2026-04-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0014_alter_post_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=500),
        ),
    ]
