# -*- coding: utf-8 -*-

HARDCODED_PROMPTS = {
    "events": [
        "Arabic NLP conferences 2026",
        "International Conference on Arabic Computational Linguistics 2026",
        "WANLP 2026 workshop on Arabic Natural Language Processing",
        "Arabic Language Technologies symposium 2026",
        "Middle East NLP research seminars 2026",
        "NLP shared tasks for Arabic dialects 2026",
        "Arabic text processing challenges 2026",
        "Computational Linguistics events in Maghreb region 2026",
        "Gulf NLP Research Expo 2026",
        "Cairo NLP summit 2026",
        "مؤتمر معالجة اللغات الطبيعية العربية 2026",
        "ورشة عمل اللسانيات الحاسوبية العربية 2026",
        "ندوة تقنيات اللغة العربية في الشرق الأوسط",
        "تحديات معالجة النصوص العربية 2026",
        "مؤتمرات الذكاء الاصطناعي للغة العربية 2026",
        "Shared tasks Arabic sentiment analysis 2026",
        "Arabic NER challenge 2026",
        "NLP workshops at ACL 2026 Arabic",
        "EMNLP 2026 Arabic NLP workshop",
        "COLING 2026 Arabic sessions",
        "Arabic machine translation competition 2026",
        "Arabic speech recognition symposium 2026",
        "Digital Humanities in Arabic research events",
        "Arabic Dialectology conferences 2026",
        "NLP in North Africa research meetings",
        "Jordanian AI and NLP conference 2026",
        "UAE NLP research forum 2026",
        "Saudi Arabic Language processing events",
        "Qatar NLP technology showcase",
        "Lebanese Arabic NLP research day",
        "Algerian NLP doctoral symposium 2026",
        "Moroccan computational linguistics workshop",
        "Tunisian NLP researchers meetup",
        "Arabic Optical Character Recognition seminar",
        "NLP for Arabic heritage documents workshop",
        "Modern Standard Arabic vs Dialect NLP conference",
        "Arabic LLM evaluation workshop 2026",
        "Generative AI for Arabic language events",
        "Arabic Chatbot development summit 2026",
        "Multilingual NLP in MENA region symposium",
        "مؤتمر الذكاء الاصطناعي واللغة العربية دبي",
        "منتدى تقنيات التعرف على الكلام العربي",
        "ورشة عمل الترجمة الآلية للغة العربية",
        "ملتقى خبراء معالجة اللغات الطبيعية 2026",
        "مؤتمر اللسانيات الحاسوبية في المغرب العربي",
        "NLP seminars site:.edu",
        "Arabic NLP workshop site:ac.uk",
        "Computational linguistics MENA site:org",
        "Arabic tech events 2026 site:gov",
        "Arabic NLP hackathon 2026"
    ],
    "tools": [
        "Arabic NLP Python libraries GitHub",
        "Arabic sentiment analysis models HuggingFace",
        "Arabic NER tools open source",
        "Arabic part-of-speech taggers GitHub",
        "Arabic text normalizer Python library",
        "Arabic lemmatization tools 2026",
        "Arabic stemmer Python package",
        "Arabic dialect identification models",
        "Arabic morphological analyzer open source",
        "CAMeL Tools GitHub repository",
        "مكتبات معالجة اللغات الطبيعية العربية GitHub",
        "نماذج تحليل المشاعر العربية HuggingFace",
        "أدوات استخراج الكيانات العربية",
        "برامج تشكيل النصوص العربية",
        "أدوات تحليل الصرف العربي مفتوحة المصدر",
        "AraBERT model variants HuggingFace",
        "MARBERT repository GitHub",
        "Arabic LLM weights download",
        "Arabic tokenizer Python GitHub",
        "Arabic stop words lists tools",
        "Arabic word embeddings tools 2026",
        "Arabic fastText models GitHub",
        "Arabic sentence transformers tools",
        "Arabic speech-to-text APIs open source",
        "Arabic text-to-speech tools 2026",
        "Arabic OCR tools GitHub",
        "Arabic handwriting recognition models",
        "Arabic question answering system tools",
        "Arabic summarization models HuggingFace",
        "Arabic machine translation scripts GitHub",
        "Farasa morphological analyzer tool",
        "MADAMIRA Arabic analyzer",
        "Qalsadi Arabic library GitHub",
        "PyArabic Python package",
        "Tashaphyne Arabic light stemmer",
        "Arabic text cleaning scripts GitHub",
        "Arabic poetry analysis tools",
        "Arabic spell checker open source",
        "Arabic diacritics restoration tools",
        "Arabic dialect mapping tools",
        "أداة الفراسة لمعالجة اللغة العربية",
        "برنامج القلصادي للغة العربية",
        "مكتبة بي أرابيك بايثون",
        "نماذج لغة عربية كبيرة مفتوحة المصدر",
        "أدوات تنقيب البيانات العربية",
        "Arabic NLP toolkit site:github.com",
        "Arabic LLM site:huggingface.co",
        "Arabic text processing site:pypi.org",
        "Arabic datasets scripts site:kaggle.com",
        "Arabic NLP research code site:edu"
    ],
    "corpus": [
        "Arabic text corpora 2026",
        "Annotated Arabic datasets for NLP",
        "Arabic dialect corpora download",
        "Modern Standard Arabic corpus open source",
        "Arabic sentiment analysis datasets",
        "Arabic NER annotated corpus",
        "Arabic machine translation parallel corpus",
        "Arabic speech datasets 2026",
        "Arabic news corpus for research",
        "Arabic social media datasets GitHub",
        "مجموعات بيانات اللغة العربية للبحث العلمي",
        "مدونات النصوص العربية المفتوحة",
        "بيانات اللهجات العربية للذكاء الاصطناعي",
        "قواعد بيانات النصوص العربية المشكلة",
        "بيانات الترجمة الآلية للغة العربية",
        "Arabic Wikipedia dump processed",
        "Arabic Common Crawl subsets",
        "Arabic OSCAR corpus research",
        "Arabic Bible and Quran parallel corpus",
        "Arabic legal documents dataset",
        "Arabic medical NLP corpus",
        "Arabic financial text dataset",
        "Arabic dialect speech corpora",
        "Levantine Arabic corpus for NLP",
        "Gulf Arabic text datasets",
        "Maghrebi Arabic annotated data",
        "Egyptian Arabic chat corpus",
        "Arabic multi-dialect parallel corpus",
        "Arabic QA datasets (TyDi QA, SQuAD Arabic)",
        "Arabic summarization gold standard corpus",
        "Arabic fake news detection dataset",
        "Arabic irony detection corpus",
        "Arabic hate speech dataset for NLP",
        "Arabic poetry dataset with meters",
        "Classical Arabic literature corpus",
        "Arabic treebank open source",
        "Arabic dependency treebank dataset",
        "Arabic coreference resolution corpus",
        "Arabic optical character recognition dataset",
        "Arabic sign language video corpus",
        "مدونة نصوص عربية معاصرة",
        "بيانات لهجات بلاد الشام",
        "مجموعة نصوص الخليج العربي",
        "مدونة اللغة العربية الفصحى",
        "بيانات منصة إكس بالعربي للبحث",
        "Arabic corpus site:edu",
        "Arabic dataset site:org",
        "Arabic text collection site:ac.ae",
        "Arabic linguistic resources site:sa",
        "Arabic NLP data site:huggingface.co"
    ],
    "courses": [
        "Arabic NLP online courses 2026",
        "Deep Learning for Arabic NLP bootcamp",
        "Arabic Computational Linguistics university courses",
        "Introduction to Arabic text processing 2026",
        "Advanced Arabic LLM training course",
        "Arabic speech recognition online training",
        "Arabic NLP for data science certifications",
        "Coursera Arabic NLP specializations",
        "EdX Arabic language technology courses",
        "Udemy Arabic NLP projects course",
        "دورات معالجة اللغات الطبيعية العربية",
        "برامج تدريبية في الذكاء الاصطناعي للغة العربية",
        "كورس معالجة النصوص العربية بايثون",
        "تدريب على اللسانيات الحاسوبية العربية",
        "دبلوم تقنيات اللغة العربية 2026",
        "Arabic NLP masters programs Europe",
        "Arabic NLP PhD courses USA",
        "NLP research training in Arab universities",
        "King Saud University NLP courses",
        "MBZUAI NLP curriculum 2026",
        "American University of Beirut NLP course",
        "Cairo University AI and NLP program",
        "Arabic NLP summer schools 2026",
        "Hands-on Arabic BERT tutorial 2026",
        "Building Arabic chatbots course",
        "Arabic text mining graduate seminar",
        "Arabic machine translation theory and practice course",
        "Arabic dialect NLP short course",
        "Python for Arabic linguistics course",
        "Arabic information retrieval course",
        "Arabic NLP on HuggingFace tutorial",
        "Arabic NLP workshop for beginners",
        "Intermediate Arabic text analysis course",
        "Advanced morphological analysis course",
        "Arabic NLP for industry professionals",
        "Arabic NLP webinar series 2026",
        "Open source Arabic NLP contributor guide",
        "Arabic NLP research methods course",
        "Ethics in Arabic NLP training",
        "Arabic data annotation certification",
        "تعليم معالجة اللغات الطبيعية للمبتدئين",
        "دورة البرمجة للغة العربية",
        "تدريب على نماذج اللغة الكبيرة",
        "كورس الذكاء الاصطناعي باللغة العربية",
        "محاضرات اللسانيات الحاسوبية",
        "Arabic NLP course site:.edu",
        "Arabic NLP tutorial site:github.io",
        "Arabic NLP training site:ac.*",
        "Arabic NLP MOOC site:coursera.org",
        "Arabic NLP workshop site:mit.edu"
    ],
    "opportunities": [
        "Arabic NLP PhD positions 2026",
        "Postdoctoral research in Arabic NLP",
        "Arabic NLP research scientist jobs",
        "Internships in Arabic language technology 2026",
        "NLP grants for Arabic research",
        "Arabic LLM research funding 2026",
        "Arabic speech technology job openings",
        "Middle East AI research careers 2026",
        "Arabic NLP engineer remote jobs",
        "Faculty positions in Computational Linguistics (Arabic)",
        "فرص بحثية في معالجة اللغات الطبيعية العربية",
        "وظائف باحثين في الذكاء الاصطناعي للعربية",
        "منح دكتوراه في اللسانيات الحاسوبية 2026",
        "تدريب عملي في تقنيات اللغة العربية",
        "وظائف معالجة اللغات الطبيعية دبي والرياض",
        "Google Research Arabic NLP internships",
        "Meta AI Arabic language research jobs",
        "Microsoft Research MENA opportunities",
        "Amazon Alexa Arabic NLP careers",
        "Apple Siri Arabic research openings",
        "Arabic NLP research assistant jobs",
        "Computational Social Science Arabic NLP projects",
        "Arabic digital humanities fellowships",
        "MENA region tech startups NLP jobs",
        "Arabic search engine engineer roles",
        "Arabic machine translation expert jobs",
        "Arabic content moderation research roles",
        "Arabic NLP project management jobs",
        "Arabic dataset curation jobs 2026",
        "Arabic linguist jobs for AI training",
        "Arabic NLP consultant opportunities",
        "PhD scholarships Arabic NLP site:edu",
        "Research fellowships Middle East site:org",
        "Arabic NLP startup funding 2026",
        "Arabic AI challenges prizes 2026",
        "Arabic NLP freelance opportunities",
        "Arabic NLP data scientist roles",
        "NLP solutions architect Arabic",
        "Arabic speech recognition expert jobs",
        "Arabic NLP academic vacancies 2026",
        "باحث في معالجة اللغات الطبيعية الرياض",
        "فرصة عمل مهندس ذكاء اصطناعي لغة عربية",
        "منحة بحثية في الإمارات العربية المتحدة",
        "تدريب صيفي في معالجة اللغات الطبيعية",
        "وظائف تقنيات اللغة في قطر",
        "Arabic NLP PhD site:university-list.net",
        "Arabic NLP jobs site:linkedin.com",
        "Arabic NLP internship site:glassdoor.com",
        "Arabic NLP grants site:nsf.gov",
        "Arabic NLP postdoc site:scholarships.com"
    ],
    "news": [
        "Latest Arabic NLP research papers 2026",
        "New Arabic LLMs announced 2026",
        "Breakthroughs in Arabic machine translation",
        "Arabic NLP state of the art results 2026",
        "Arabic speech recognition news updates",
        "MENA region AI policy announcements 2026",
        "Arabic dataset releases news 2026",
        "Arabic NLP community news and events",
        "Arabic AI startups news 2026",
        "National Arabic language technology initiatives",
        "أخبار أبحاث معالجة اللغات الطبيعية العربية",
        "إطلاق نماذج لغة عربية جديدة 2026",
        "تطورات تقنيات اللغة العربية والذكاء الاصطناعي",
        "أحدث مجموعات البيانات العربية المتاحة",
        "مبادرات وطنية لخدمة اللغة العربية تقنياً",
        "ArXiv Arabic NLP recent submissions",
        "ACL 2026 Arabic research highlights",
        "EMNLP 2026 Arabic paper awards",
        "Arabic NLP research lab announcements",
        "New tools for Arabic dialect processing news",
        "Arabic LLM performance benchmarks news",
        "Arabic NLP for healthcare news 2026",
        "Arabic legal NLP developments 2026",
        "Digital Arabic content growth statistics",
        "Arabic social media trends analysis news",
        "Arabic hate speech detection research news",
        "Arabic sentiment analysis for business news",
        "Arabic NLP in education news 2026",
        "New Arabic OCR technology news",
        "Arabic sign language AI news 2026",
        "Arabic voice assistant updates 2026",
        "Arabic NLP for finance research news",
        "Ethical AI for Arabic language news",
        "Arabic NLP infrastructure investments",
        "MENA tech ecosystem AI news",
        "Arabic NLP collaborations global news",
        "Arabic NLP journals and publications",
        "Arabic NLP dataset competition winners",
        "Arabic NLP for accessibility news",
        "Arabic language preservation through AI news",
        "أبحاث جامعة الملك عبد الله للعلوم والتقنية",
        "أخبار مركز كيو أر آي للبحوث قطر",
        "تطورات الذكاء الاصطناعي في الإمارات",
        "إنجازات معالجة اللغة العربية في مصر",
        "أخبار اللسانيات الحاسوبية في الأردن",
        "Arabic NLP research site:arxiv.org",
        "Arabic NLP news site:techcrunch.com",
        "Arabic AI news site:forbes.com",
        "Arabic tech news site:aljazeera.net",
        "Arabic NLP updates site:medium.com"
    ]
}
