# Generated by Django 5.1.7 on 2025-10-03 16:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('blocked', 'Bloqué')], default='pending', max_length=20, verbose_name='Statut du compte')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Photo de profil')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('speciality', models.CharField(blank=True, choices=[('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('nlp', 'Traitement du Langage Naturel (NLP)'), ('computer_vision', 'Vision par Ordinateur'), ('reinforcement_learning', 'Apprentissage par Renforcement'), ('ai_ethics', "Éthique de l'IA"), ('robotics', 'Robotique et IA'), ('neural_networks', 'Réseaux de Neurones'), ('ai_security', "Sécurité de l'IA"), ('ai_healthcare', 'IA en Santé'), ('ai_finance', 'IA en Finance'), ('ai_education', 'IA en Éducation'), ('ai_transport', 'IA dans les Transports'), ('ai_agriculture', 'IA en Agriculture'), ('ai_energy', "IA dans l'Énergie"), ('ai_manufacturing', 'IA dans la Production'), ('ai_research', 'Recherche Fondamentale en IA'), ('autre', "Autre Domaine de l'IA")], max_length=100, null=True, verbose_name='Spécialité')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Profil vérifié')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
