# Generated by Django 5.1.7 on 2025-10-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(blank=True, choices=[('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('nlp', 'Traitement du Langage Naturel (NLP)'), ('computer_vision', 'Vision par Ordinateur'), ('reinforcement_learning', 'Apprentissage par Renforcement'), ('ai_ethics', "Éthique de l'IA"), ('robotics', 'Robotique et IA'), ('neural_networks', 'Réseaux de Neurones'), ('ai_security', "Sécurité de l'IA"), ('ai_healthcare', 'IA en Santé'), ('ai_finance', 'IA en Finance'), ('ai_education', 'IA en Éducation'), ('ai_transport', 'IA dans les Transports'), ('ai_agriculture', 'IA en Agriculture'), ('ai_energy', "IA dans l'Énergie"), ('ai_manufacturing', 'IA dans la Production'), ('ai_research', 'Recherche Fondamentale en IA'), ('autre', "Autre Domaine de l'IA")], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('blocked', 'Bloqué')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
