# Generated by Django 5.1.7 on 2025-11-16 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar_alter_customuser_email_and_more'),
        ('institutions', '0003_alter_specialty_options_remove_specialty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='email verification code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution', verbose_name='institution'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(blank=True, choices=[('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('nlp', 'Natural Language Processing (NLP)'), ('computer_vision', 'Computer Vision'), ('reinforcement_learning', 'Reinforcement Learning'), ('ai_ethics', 'AI Ethics'), ('robotics', 'Robotics and AI'), ('neural_networks', 'Neural Networks'), ('ai_security', 'AI Security'), ('ai_healthcare', 'AI in Healthcare'), ('ai_finance', 'AI in Finance'), ('ai_education', 'AI in Education'), ('ai_transport', 'AI in Transportation'), ('ai_agriculture', 'AI in Agriculture'), ('ai_energy', 'AI in Energy'), ('ai_manufacturing', 'AI in Manufacturing'), ('ai_research', 'Fundamental AI Research'), ('autre', 'Other AI Field')], max_length=100, null=True, verbose_name='field of specialization in AI'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
