# Generated by Django 5.1.7 on 2026-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio_ar',
            field=models.TextField(blank=True, default='', verbose_name='Biography (Arabic)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_en',
            field=models.TextField(blank=True, default='', verbose_name='Biography (English)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name_ar',
            field=models.CharField(blank=True, default='', help_text='Full name in Arabic', max_length=255, verbose_name='Full Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name_en',
            field=models.CharField(blank=True, default='', help_text='Full name in English', max_length=255, verbose_name='Full Name (English)'),
        ),
    ]
