# Generated by Django 5.1.7 on 2026-02-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_twofactorauth'),
    ]

    operations = [
    ]
