# Generated by Django 5.1.7 on 2026-02-14 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260207_2355'),
        ('institutions', '0009_add_bilingual_city_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution', verbose_name='institution'),
        ),
    ]
