# Generated by Django 5.1.7 on 2026-03-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_show_online_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendship',
            new_name='accounts_fr_request_ca3f99_idx',
            old_name='accounts_fr_request_a3ba9b_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='accounts_fr_address_a49795_idx',
            old_name='accounts_fr_address_3e8b0a_idx',
        ),
    ]
