# Generated by Django 5.1.15 on 2026-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_experience_project_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experience',
            new_name='accounts_ex_user_id_2d8866_idx',
            old_name='accounts_ex_user_id_5d5f92_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='accounts_fo_followe_6d6ab4_idx',
            old_name='accounts_fo_followe_3e3e69_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='accounts_fo_followi_60a153_idx',
            old_name='accounts_fo_followi_127f0d_idx',
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('professional', 'Professional'), ('project', 'Project'), ('event', 'Event'), ('volunteer', 'Volunteer'), ('internship', 'Internship')], default='professional', max_length=20),
        ),
    ]
