# Generated by Django 5.1.7 on 2026-02-21 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=255, verbose_name='Object ID')),
                ('content_title', models.CharField(blank=True, default='', max_length=500, verbose_name='Content Title')),
                ('content_url', models.CharField(blank=True, default='', max_length=1000, verbose_name='Content URL')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('seen', 'Seen')], default='sent', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Seen At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_replies', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='sharing.share', verbose_name='Share')),
            ],
            options={
                'verbose_name': 'Share Reply',
                'verbose_name_plural': 'Share Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['receiver', '-created_at'], name='sharing_sha_receive_57278f_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['sender', '-created_at'], name='sharing_sha_sender__f855f2_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['content_type', 'object_id'], name='sharing_sha_content_a43c51_idx'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver', 'content_type', 'object_id'), name='unique_share_per_pair'),
        ),
    ]
