# Generated by Django 5.1.7 on 2026-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTopic',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Topic',
                'verbose_name_plural': 'Pending Topics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('forum.topic',),
        ),
        migrations.AddField(
            model_name='topic',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (English)'),
        ),
    ]
