# Generated by Django 5.1.7 on 2026-02-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_pendingtopic_topic_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (English)'),
        ),
    ]
