# Generated by Django 5.1.7 on 2026-02-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_add_chatroom_bilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
