# Generated by Django 5.1.7 on 2026-02-20 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_missing_post_fields(apps, schema_editor):
    Post = apps.get_model("QA", "Post")
    table_name = Post._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    fields_to_add = {
        "approval_date": models.DateTimeField(
            blank=True, null=True, verbose_name="Approval Date"
        ),
        "approved_by": models.ForeignKey(
            settings.AUTH_USER_MODEL,
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name="approved_posts",
            verbose_name="Approved By",
        ),
        "rejection_reason": models.TextField(
            blank=True, default="", verbose_name="Rejection Reason"
        ),
        "view_count": models.PositiveIntegerField(
            default=0, verbose_name="View Count"
        ),
    }

    for field_name, field in fields_to_add.items():
        field.set_attributes_from_name(field_name)
        column_name = field.column
        if column_name in existing_columns:
            continue
        schema_editor.add_field(Post, field)


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0005_domain_model_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_missing_post_fields, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='post',
                    name='approval_date',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date'),
                ),
                migrations.AddField(
                    model_name='post',
                    name='approved_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_posts', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
                ),
                migrations.AddField(
                    model_name='post',
                    name='rejection_reason',
                    field=models.TextField(blank=True, default='', verbose_name='Rejection Reason'),
                ),
                migrations.AddField(
                    model_name='post',
                    name='view_count',
                    field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
                ),
            ],
        ),
    ]
