# Generated by Django 5.1.7 on 2026-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0007_post_dedup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='news_category',
            field=models.CharField(choices=[('paper', 'Paper'), ('news', 'News'), ('announcement', 'Announcement'), ('blog', 'Blog')], default='paper', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/thumbnails/'),
        ),
    ]
