<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-03-26 20:58
=======
# Generated by Django 5.1.15 on 2026-03-26 20:36
>>>>>>> NEWDESIGN

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0009_post_authors_post_news_category_post_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, default=''),
        ),
    ]
