from scraping.models import ScrapingSource

categories_and_sources = {
    "events": [
        ("ACL Anthology", "https://aclanthology.org/", "NLP conference proceedings and upcoming events"),
        ("NAACL", "https://naacl.org/", "North American Chapter of the Association for Computational Linguistics"),
        ("EMNLP", "https://emnlp.org/", "Conference on Empirical Methods in Natural Language Processing"),
        ("EACL", "https://eacl.org/", "European Chapter of the ACL"),
        ("LREC", "https://lrec-conf.org/", "Language Resources and Evaluation Conference"),
        ("COLING", "https://coling.org/", "International Conference on Computational Linguistics"),
        ("AACL", "https://aaclweb.org/", "Asia-Pacific Chapter of the ACL"),
        ("SIGDIAL", "https://www.sigdial.org/", "Special Interest Group on Discourse and Dialogue"),
        ("Interspeech", "https://interspeech.org/", "International Conference on Spoken Language Processing"),
        ("ICASSP", "https://signalprocessingsociety.org/events/icassp", "IEEE International Conference on Acoustics, Speech and Signal Processing"),
        ("IWSLT", "https://iwslt.org/", "International Workshop on Spoken Language Translation"),
        ("WMT", "https://statmt.org/wmt23/", "Conference on Machine Translation"),
        ("Arabic NLP (WANLP)", "https://wanlp2024.sigarab.org/", "Workshop on Arabic Natural Language Processing"),
        ("SIGARAB", "https://sigarab.org/events", "ACL Special Interest Group on Arabic NLP"),
        ("CamelLab Events", "https://camel.abudhabi.nyu.edu/", "NYU Abu Dhabi CAMEL Lab Events"),
        ("Osool NLP", "https://osool.nlp.org/", "Osool Conference on Arabic Language Computing"),
        ("MIGRATE NLP", "https://migrate.eu/", "MIGRATE Arabic NLP events"),
        ("WikiCFP - NLP", "http://www.wikicfp.com/cfp/call?conf=NLP", "WikiCFP for NLP"),
        ("WikiCFP - Arabic NLP", "http://www.wikicfp.com/cfp/call?conf=Arabic%20NLP", "WikiCFP for Arabic NLP"),
        ("KSU NLP Events", "https://nlp.ksu.edu.sa/events", "King Saud University NLP Events"),
    ],
    "tools": [
        ("HuggingFace - Arabic", "https://huggingface.co/models?language=ar", "Arabic models on HuggingFace"),
        ("CamelTools", "https://github.com/CAMeL-Lab/camel_tools", "A suite of Arabic NLP tools"),
        ("Farasa", "https://farasa.qcri.org/", "QCRI Arabic NLP toolkit"),
        ("AraBERT", "https://github.com/aub-mind/arabert", "Pretrained BERT models for Arabic"),
        ("Maha", "https://github.com/Qatar-Computing-Research-Institute/Maha", "Maha Arabic text processing"),
        ("PyArabic", "https://github.com/linuxscout/pyarabic", "Python Arabic library"),
        ("Tashaphyne", "https://github.com/linuxscout/tashaphyne", "Arabic Light Stemmer"),
        ("Qalsadi", "https://github.com/linuxscout/qalsadi", "Arabic Morphological Analyzer"),
        ("Stanza - Arabic", "https://stanfordnlp.github.io/stanza/available_models.html", "Stanford Stanza Arabic models"),
        ("spaCy - Arabic", "https://spacy.io/models/ar", "spaCy Arabic models"),
        ("Trankit", "https://github.com/nlp-uoregon/trankit", "Trankit NLP toolkit supporting Arabic"),
        ("NLTK", "https://www.nltk.org/", "Natural Language Toolkit"),
        ("Gensim", "https://radimrehurek.com/gensim/", "Topic modelling for humans"),
        ("Transformers", "https://github.com/huggingface/transformers", "State-of-the-art Machine Learning for Pytorch, TensorFlow, and JAX"),
        ("LangChain", "https://github.com/hwchase17/langchain", "Building applications with LLMs through composability"),
        ("LlamaIndex", "https://github.com/jerryjliu/llama_index", "Data framework for LLM applications"),
        ("Haystack", "https://github.com/deepset-ai/haystack", "End-to-end NLP framework for search"),
        ("Mishkal", "https://github.com/linuxscout/mishkal", "Arabic text diacritization"),
        ("Shakkala", "https://github.com/Barqawiz/Shakkala", "Arabic text vocalization/diacritization"),
        ("AraT5", "https://github.com/UBC-NLP/araT5", "Arabic T5 models"),
    ],
    "courses": [
        ("Coursera - NLP", "https://www.coursera.org/courses?query=natural%20language%20processing", "NLP courses on Coursera"),
        ("edX - NLP", "https://www.edx.org/learn/natural-language-processing", "NLP courses on edX"),
        ("DeepLearning.AI NLP", "https://www.deeplearning.ai/courses/natural-language-processing-specialization/", "NLP Specialization"),
        ("Stanford CS224n", "http://web.stanford.edu/class/cs224n/", "Natural Language Processing with Deep Learning"),
        ("HuggingFace NLP Course", "https://huggingface.co/course/chapter1/1", "HuggingFace Course"),
        ("Fast.ai NLP", "https://www.fast.ai/posts/2019-07-08-fastai-nlp.html", "A Code-First Introduction to NLP"),
        ("CMU CS 11-747", "http://phontron.com/class/nn4nlp2021/", "Neural Networks for NLP"),
        ("Princeton COS 484", "https://www.cs.princeton.edu/courses/archive/spring20/cos484/", "Natural Language Processing"),
        ("Udacity - NLP", "https://www.udacity.com/course/natural-language-processing-nanodegree--nd892", "NLP Nanodegree"),
        ("Udemy - Arabic NLP", "https://www.udemy.com/topic/natural-language-processing/", "NLP courses on Udemy"),
        ("Edraak - AI", "https://www.edraak.org/en/programs/specialization/ai-1/", "AI specialization on Edraak"),
        ("Rwaq - AI", "https://www.rwaq.org/categories/computer-science", "Computer science courses on Rwaq"),
        ("MIT 6.864", "https://ocw.mit.edu/courses/6-864-advanced-natural-language-processing-fall-2005/", "Advanced NLP"),
        ("Berkeley CS288", "https://nlp.cs.berkeley.edu/", "Statistical NLP"),
        ("Oxford Deep NLP", "https://github.com/oxford-cs-deepnlp-2017/lectures", "Deep Learning for NLP"),
        ("UMass CS 685", "https://people.cs.umass.edu/~miyyer/cs685/", "Advanced NLP"),
        ("Washington CSE 517", "https://courses.cs.washington.edu/courses/cse517/21wi/", "NLP"),
        ("Cornell CS 6740", "https://www.cs.cornell.edu/courses/cs6740/2021fa/", "Advanced Language Technologies"),
        ("Kaggle - NLP", "https://www.kaggle.com/learn/natural-language-processing", "NLP mini-course on Kaggle"),
        ("DataCamp - NLP", "https://www.datacamp.com/tracks/natural-language-processing-in-python", "NLP track on DataCamp"),
    ],
    "news": [
        ("VentureBeat - AI", "https://venturebeat.com/category/ai/", "AI News on VentureBeat"),
        ("TechCrunch - AI", "https://techcrunch.com/category/artificial-intelligence/", "AI News on TechCrunch"),
        ("MIT Tech Review - AI", "https://www.technologyreview.com/topic/artificial-intelligence/", "AI News MIT Tech Review"),
        ("Synced", "https://syncedreview.com/", "AI Technology & Industry News"),
        ("Towards Data Science", "https://towardsdatascience.com/nlp/home", "NLP section of TDS"),
        ("KDnuggets", "https://www.kdnuggets.com/tag/nlp", "Data Science and NLP News"),
        ("Slator", "https://slator.com/", "Language Industry News"),
        ("MultiLingual", "https://multilingual.com/", "Language Tech and Localization News"),
        ("AI News", "https://artificialintelligence-news.com/", "AI News"),
        ("The Batch", "https://www.deeplearning.ai/the-batch/", "DeepLearning.AI Newsletter"),
        ("NLP News - Sebastian Ruder", "https://nlpnews.substack.com/", "Sebastian Ruder's NLP Newsletter"),
        ("Import AI", "https://importai.substack.com/", "Jack Clark's AI Newsletter"),
        ("Ahead of AI", "https://magazine.sebastianraschka.com/", "Sebastian Raschka's Newsletter"),
        ("The Sequence", "https://thesequence.substack.com/", "AI Newsletter"),
        ("InfoQ - AI", "https://www.infoq.com/ai-ml-data-eng/news/", "AI/ML News on InfoQ"),
        ("Hacker News - AI", "https://news.ycombinator.com/", "Search HN for AI/NLP news"),
        ("Analytics Vidhya", "https://www.analyticsvidhya.com/blog/category/nlp/", "NLP Blog on Analytics Vidhya"),
        ("arXiv cs.CL", "https://arxiv.org/list/cs.CL/recent", "Recent NLP papers on arXiv"),
        ("Papers with Code", "https://paperswithcode.com/area/natural-language-processing", "Trending NLP research"),
        ("Majarra - AI", "https://my.majarra.com/", "Arabic Technology News"),
    ],
    "opportunities": [
        ("LinkedIn Jobs - NLP", "https://www.linkedin.com/jobs/search/?keywords=Natural%20Language%20Processing", "NLP Jobs on LinkedIn"),
        ("LinkedIn Jobs - Arabic NLP", "https://www.linkedin.com/jobs/search/?keywords=Arabic%20NLP", "Arabic NLP Jobs on LinkedIn"),
        ("Indeed - NLP", "https://www.indeed.com/q-Natural-Language-Processing-jobs.html", "NLP Jobs on Indeed"),
        ("Glassdoor - NLP", "https://www.glassdoor.com/Job/nlp-jobs-SRCH_KO0,3.htm", "NLP Jobs on Glassdoor"),
        ("Google Careers - AI", "https://careers.google.com/jobs/results/?skills=Artificial%20Intelligence", "AI Jobs at Google"),
        ("Microsoft Careers - AI", "https://careers.microsoft.com/us/en/search-results?keywords=AI", "AI Jobs at Microsoft"),
        ("Meta Careers - AI", "https://www.metacareers.com/jobs/?skills=Artificial%20Intelligence", "AI Jobs at Meta"),
        ("Amazon Jobs - Applied Scientist", "https://www.amazon.jobs/en/job_categories/machine-learning-science", "Machine Learning Jobs at Amazon"),
        ("Apple Careers - ML", "https://jobs.apple.com/en-us/search?search=Machine%20Learning", "ML Jobs at Apple"),
        ("HuggingFace Jobs", "https://huggingface.co/join", "Jobs at HuggingFace"),
        ("DeepMind Jobs", "https://deepmind.google/about/careers/", "Jobs at DeepMind"),
        ("OpenAI Jobs", "https://openai.com/careers/", "Jobs at OpenAI"),
        ("Anthropic Jobs", "https://www.anthropic.com/careers", "Jobs at Anthropic"),
        ("Cohere Jobs", "https://cohere.com/careers", "Jobs at Cohere"),
        ("AI2 Jobs", "https://allenai.org/careers", "Jobs at Allen Institute for AI"),
        ("MBZUAI Careers", "https://mbzuai.ac.ae/careers/", "Careers at MBZUAI"),
        ("Qatar Computing Research Institute", "https://www.hbku.edu.qa/en/qcri/careers", "Careers at QCRI"),
        ("KACST Careers", "https://careers.kacst.gov.sa/", "Careers at KACST"),
        ("SDAIA Careers", "https://sdaia.gov.sa/en/SDAIA/careers/", "Careers at SDAIA"),
        ("Wuzzuf - Data Science", "https://wuzzuf.net/search/jobs/?q=data+science", "Data Science Jobs in Egypt"),
    ],
    "corpus": [
        ("HuggingFace Datasets - Arabic", "https://huggingface.co/datasets?language=ar", "Arabic datasets on HuggingFace"),
        ("LDC Catalog", "https://catalog.ldc.upenn.edu/", "Linguistic Data Consortium"),
        ("ELRA Catalog", "http://catalog.elra.info/en-us/", "European Language Resources Association"),
        ("OSIAN", "https://osian.eu/", "Open Source International Arabic News Corpus"),
        ("OSCAR", "https://oscar-project.org/", "Open Super-large Crawled ALMAnaCH coRpus"),
        ("Tashkeela", "https://sourceforge.net/projects/tashkeela/", "Arabic diacritized text corpus"),
        ("Wadi", "https://github.com/WadiCorpus", "Wadi Arabic Corpus"),
        ("KSUCCA", "https://github.com/ksucca", "King Saud University Corpus of Classical Arabic"),
        ("Arabic Learner Corpus", "https://www.arabiclearnercorpus.com/", "Corpus of Arabic learner texts"),
        ("Abu El-Khair Corpus", "http://www.abuelkhair.net/index.php/corpus/", "Huge Arabic text corpus"),
        ("NADI Shared Task", "https://nadi.sigarab.org/", "Nuanced Arabic Dialect Identification"),
        ("QADI", "https://github.com/mxs1204/QADI", "Qatar Arabic Dialect Identification dataset"),
        ("HARD", "https://github.com/elnagara/HARD-Arabic-Dataset", "Hotel Arabic-Reviews Dataset"),
        ("BRONZE", "https://github.com/bronze-dataset", "Arabic reading comprehension"),
        ("ARCD", "https://github.com/husseinmozannar/ARCD", "Arabic Reading Comprehension Dataset"),
        ("TyDi QA", "https://github.com/google-research-datasets/tydiqa", "Typologically Diverse Question Answering"),
        ("MLQA", "https://github.com/facebookresearch/MLQA", "Multilingual Question Answering"),
        ("XQuAD", "https://github.com/deepmind/xquad", "Cross-lingual Question Answering Dataset"),
        ("ArSAS", "https://github.com/KSU-DMIS/ArSAS", "Arabic Speech Act and Sentiment Corpus"),
        ("Multi-Domain Arabic Resources", "https://github.com/camel-tools/camel-data", "Various datasets maintained by CAMeL Lab"),
    ],
}

added_count = 0
for cat, sources in categories_and_sources.items():
    for name, url, desc in sources:
        obj, created = ScrapingSource.objects.get_or_create(
            category=cat,
            url=url,
            defaults={"name": name, "description": desc, "is_active": True}
        )
        if created:
            added_count += 1
print(f"Added {added_count} sources successfully!")
