# Generated by Django 5.1.7 on 2025-10-03 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='date')),
                ('users_count', models.IntegerField(default=0, verbose_name="nombre d'utilisateurs")),
                ('publications_count', models.IntegerField(default=0, verbose_name='nombre de publications')),
                ('corpora_count', models.IntegerField(default=0, verbose_name='nombre de corpus')),
                ('tools_count', models.IntegerField(default=0, verbose_name="nombre d'outils")),
                ('projects_count', models.IntegerField(default=0, verbose_name='nombre de projets')),
                ('forum_posts_count', models.IntegerField(default=0, verbose_name='nombre de messages forum')),
                ('visits_count', models.IntegerField(default=0, verbose_name='nombre de visites')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='nombre de téléchargements')),
            ],
            options={
                'verbose_name': 'statistique',
                'verbose_name_plural': 'statistiques',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Support'), ('suggestion', 'Suggestion'), ('bug', 'Bug Report'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=10, verbose_name='Ancien statut')),
                ('new_status', models.CharField(max_length=10, verbose_name='Nouveau statut')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['-change_date'],
            },
        ),
    ]
