# Generated by Django 5.1.7 on 2026-03-05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_snapshot", models.CharField(default="user", max_length=32)),
                ("action", models.CharField(max_length=120)),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("http_method", models.CharField(blank=True, default="GET", max_length=10)),
                ("target_type", models.CharField(blank=True, default="", max_length=80)),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("details", models.TextField(blank=True, default="")),
                ("ip_address", models.CharField(blank=True, default="", max_length=64)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("occurred_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin activity log",
                "verbose_name_plural": "Admin activity logs",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["admin_user", "occurred_at"], name="pages_adminlog_user_time_idx"),
                    models.Index(fields=["action", "occurred_at"], name="pages_adminlog_action_time_idx"),
                ],
            },
        ),
    ]
