# Generated by Django 5.1.7 on 2026-03-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_securitylog_failed_login_choice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminactivitylog',
            new_name='pages_admin_admin_u_e3a4a0_idx',
            old_name='pages_adminlog_user_time_idx',
        ),
        migrations.RenameIndex(
            model_name='adminactivitylog',
            new_name='pages_admin_action_abfb24_idx',
            old_name='pages_adminlog_action_time_idx',
        ),
        migrations.RenameIndex(
            model_name='blockedupload',
            new_name='pages_block_blocked_f038f7_idx',
            old_name='pages_blocke_blocked_5e25c3_idx',
        ),
        migrations.RenameIndex(
            model_name='blockedupload',
            new_name='pages_block_ip_addr_29f257_idx',
            old_name='pages_blocke_ip_addr_957baa_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='pages_secur_created_7cea34_idx',
            old_name='pages_secur_created_0d0706_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='pages_secur_action_26434f_idx',
            old_name='pages_secur_action__95e6f4_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='pages_secur_role_9f7518_idx',
            old_name='pages_secur_role_43e7d0_idx',
        ),
    ]
