# Generated by Django 5.1.15 on 2026-04-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_opportunity_scrape_update_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newspublication',
            new_name='pages_newsp_type_f500ca_idx',
            old_name='pages_newsp_type_4cbbc1_idx',
        ),
        migrations.RenameIndex(
            model_name='newspublication',
            new_name='pages_newsp_year_910e19_idx',
            old_name='pages_newsp_year_654c4f_idx',
        ),
        migrations.RenameIndex(
            model_name='newspublication',
            new_name='pages_newsp_created_b92c69_idx',
            old_name='pages_newsp_create_3d07e8_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='pages_oppor_status_60bb17_idx',
            old_name='pages_oppor_status_8dc9f4_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='pages_oppor_approva_87ffe2_idx',
            old_name='pages_oppor_approva_3da984_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='pages_oppor_created_54d99b_idx',
            old_name='pages_oppor_created_3778d0_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='pages_oppor_deadlin_f931a7_idx',
            old_name='pages_oppor_deadlin_04b584_idx',
        ),
    ]
