# Generated by Django 5.1.7 on 2026-02-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_ar',
            field=models.TextField(blank=True, default='', verbose_name='Message (Arabic)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(blank=True, default='', verbose_name='Message (English)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('PROJECT_INVITATION', 'Project Invitation'), ('MEMBERSHIP_REQUEST', 'Membership Request'), ('PROJECT_UPDATE', 'Project Update'), ('TASK_ASSIGNED', 'Task Assigned'), ('LEAVE_REQUEST', 'Leave Request'), ('COMMENT', 'Comment'), ('MESSAGE', 'Message'), ('EVENT_CREATED', 'Event Created'), ('EVENT_APPROVED', 'Event Approved'), ('RESOURCE_ADDED', 'New Resource'), ('TOOL_ADDED', 'New Tool'), ('CORPUS_UPDATE', 'Corpus Update'), ('RESEARCH_UPDATE', 'Research Update'), ('FORUM_TOPIC', 'Forum Topic'), ('QA_ANSWER', 'Q&A Answer'), ('QA_COMMENT', 'Q&A Comment'), ('POST_APPROVED', 'Post Approved'), ('INSTITUTION_UPDATE', 'Institution Update')], default='SYSTEM', max_length=50),
        ),
    ]
