# Generated by Django 5.1.7 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System"),
                    ("CONTENT_APPROVED", "Content Approved"),
                    ("CONTENT_REJECTED", "Content Rejected"),
                    ("PROJECT_INVITATION", "Project Invitation"),
                    ("MEMBERSHIP_REQUEST", "Membership Request"),
                    ("PROJECT_UPDATE", "Project Update"),
                    ("TASK_ASSIGNED", "Task Assigned"),
                    ("LEAVE_REQUEST", "Leave Request"),
                    ("FOLLOW_REQUEST", "Follow Request"),
                    ("COMMENT", "Comment"),
                    ("MESSAGE", "Message"),
                    ("EVENT_CREATED", "Event Created"),
                    ("EVENT_APPROVED", "Event Approved"),
                    ("RESOURCE_ADDED", "New Resource"),
                    ("TOOL_ADDED", "New Tool"),
                    ("CORPUS_UPDATE", "Corpus Update"),
                    ("RESEARCH_UPDATE", "Research Update"),
                    ("FORUM_TOPIC", "Forum Topic"),
                    ("BAN", "Ban Notification"),
                    ("QA_ANSWER", "Q&A Answer"),
                    ("QA_COMMENT", "Q&A Comment"),
                    ("POST_APPROVED", "Post Approved"),
                    ("INSTITUTION_UPDATE", "Institution Update"),
                ],
                default="SYSTEM",
                max_length=50,
            ),
        ),
    ]
