# Generated by Django 5.1.7 on 2026-03-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0005_message_system_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='direct_mess_user1_i_db90e0_idx',
            old_name='direct_mess_user1_i_1a91ff_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='direct_mess_user2_i_d2e08c_idx',
            old_name='direct_mess_user2_i_b06c6f_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='direct_mess_convers_cab827_idx',
            old_name='direct_mess_convers_a4e816_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationparticipant',
            new_name='direct_mess_convers_50a835_idx',
            old_name='direct_mess_convers_75c0dc_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationparticipant',
            new_name='direct_mess_user_id_826a31_idx',
            old_name='direct_mess_user_id_b5a5af_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='direct_mess_convers_7ff487_idx',
            old_name='direct_mess_convers_913f85_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='direct_mess_convers_dc4cb1_idx',
            old_name='direct_mess_convers_3ea58c_idx',
        ),
    ]
