# Generated by Django 5.1.7 on 2025-10-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_en'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(default='', max_length=100, verbose_name='Country Name (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Country Name (English)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Country Code'),
        ),
    ]
