# Generated by Django 5.1.7 on 2025-10-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_country_options_remove_country_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name_en'], 'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='name',
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Specialty Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Specialty Name (English)'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Specialty Code'),
        ),
    ]
