# Generated by Django 5.1.7 on 2025-12-01 14:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_specialty_options_remove_specialty_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name_en'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='name',
        ),
        migrations.AddField(
            model_name='institution',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Institution Name (English)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(default='default.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='institution_pics'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='institutions/logos/', verbose_name='Logo'),
        ),
    ]
