# Generated by Django 5.1.7 on 2025-12-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_restore_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution Name (English)'),
        ),
    ]
