# Generated by Django 5.1.7 on 2025-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_institution_name_ar_institution_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='institution_pics'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name='Logo'),
        ),
    ]
