# Generated by Django 5.1.7 on 2026-02-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_institution_name_ar_institution_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
    ]
