# Generated by Django 5.1.7 on 2026-02-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_add_bilingual_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address_ar',
            field=models.TextField(blank=True, default='', verbose_name='Address (Arabic)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address_en',
            field=models.TextField(blank=True, default='', verbose_name='Address (English)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='city_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City (Arabic)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='city_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City (English)'),
        ),
    ]
