# Generated by Django 5.1.7 on 2026-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_add_bilingual_city_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Institution must be approved by admin before being publicly visible', max_length=20, verbose_name='Approval Status'),
        ),
    ]
