# Generated by Django 5.1.7 on 2026-03-22

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0010_add_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="ror_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name=_("ROR ID"),
            ),
        ),
    ]
