# Generated by Django 5.1.7 on 2026-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_institution_ror_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='affiliated_researchers_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Affiliated Researchers Count'),
        ),
        migrations.AddField(
            model_name='institution',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='institution',
            name='founding_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Founding Year'),
        ),
        migrations.AddField(
            model_name='institution',
            name='notable_publications',
            field=models.JSONField(blank=True, null=True, verbose_name='Notable Publications'),
        ),
        migrations.AddField(
            model_name='institution',
            name='social_links',
            field=models.JSONField(blank=True, null=True, verbose_name='Social Links'),
        ),
        migrations.AddField(
            model_name='institution',
            name='source_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Source Name'),
        ),
        migrations.AddField(
            model_name='institution',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Source URL'),
        ),
    ]
