# Generated by Django 5.1.7 on 2025-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='title_ar',
            field=models.CharField(blank=True, default='', help_text='Arabic title of the resource', max_length=200, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='English title of the resource', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ar',
            field=models.CharField(blank=True, default='', help_text='Arabic title of the resource', max_length=200, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='English title of the resource', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ar',
            field=models.CharField(blank=True, default='', help_text='Arabic title of the resource', max_length=200, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='English title of the resource', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='title_ar',
            field=models.CharField(blank=True, default='', help_text='Arabic title of the resource', max_length=200, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='English title of the resource', max_length=200, verbose_name='Title (English)'),
        ),
    ]
