# Generated by Django 5.1.7 on 2026-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_corpus_title_ar_corpus_title_en_course_title_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCorpus',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Corpus',
                'verbose_name_plural': 'Pending Corpora',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.corpus',),
        ),
        migrations.CreateModel(
            name='PendingCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Course',
                'verbose_name_plural': 'Pending Courses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.course',),
        ),
        migrations.CreateModel(
            name='PendingDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Document',
                'verbose_name_plural': 'Pending Documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.document',),
        ),
        migrations.CreateModel(
            name='PendingNLPTool',
            fields=[
            ],
            options={
                'verbose_name': 'Pending NLP Tool',
                'verbose_name_plural': 'Pending NLP Tools',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.nlptool',),
        ),
        migrations.AddField(
            model_name='corpus',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Content must be approved by admin before being publicly visible', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='description_ar',
            field=models.TextField(blank=True, default='', help_text='Arabic description of the resource', verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='English description of the resource', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='course',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Content must be approved by admin before being publicly visible', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ar',
            field=models.TextField(blank=True, default='', help_text='Arabic description of the resource', verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='English description of the resource', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='document',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Content must be approved by admin before being publicly visible', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ar',
            field=models.TextField(blank=True, default='', help_text='Arabic description of the resource', verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='English description of the resource', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Content must be approved by admin before being publicly visible', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='description_ar',
            field=models.TextField(blank=True, default='', help_text='Arabic description of the resource', verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='English description of the resource', verbose_name='Description (English)'),
        ),
    ]
