# Generated by Django 5.1.7 on 2026-02-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_pendingcorpus_pendingcourse_pendingdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Upload a document (PDF, DOCX, TXT, etc.)', null=True, upload_to='resources/files/%Y/%m/', verbose_name='Uploaded File'),
        ),
        migrations.AddField(
            model_name='course',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Upload a document (PDF, DOCX, TXT, etc.)', null=True, upload_to='resources/files/%Y/%m/', verbose_name='Uploaded File'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Upload a document (PDF, DOCX, TXT, etc.)', null=True, upload_to='resources/files/%Y/%m/', verbose_name='Uploaded File'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Upload a document (PDF, DOCX, TXT, etc.)', null=True, upload_to='resources/files/%Y/%m/', verbose_name='Uploaded File'),
        ),
    ]
