# Generated by Django 5.1.7 on 2026-02-14 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_add_bilingual_city_address'),
        ('resources', '0005_add_prerequisites_syllabus_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(help_text='University or school offering the course', on_delete=django.db.models.deletion.PROTECT, to='institutions.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='memoir',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institution', verbose_name='Institution'),
        ),
    ]
