# Generated by Django 5.1.7 on 2026-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_course_institution_alter_memoir_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Legacy field - use approval_status instead', verbose_name='Is Approved (Legacy)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Legacy field - use approval_status instead', verbose_name='Is Approved (Legacy)'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Legacy field - use approval_status instead', verbose_name='Is Approved (Legacy)'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Legacy field - use approval_status instead', verbose_name='Is Approved (Legacy)'),
        ),
    ]
