# Generated by Django 5.1.7 on 2026-02-25 18:19

from django.db import migrations


def make_rejection_reason_nullable(apps, schema_editor):
    """
    Add rejection_reason column if missing, or make it nullable if it exists.
    """
    tables = [
        'resources_corpus',
        'resources_course',
        'resources_nlptool',
        'resources_document',
    ]
    with schema_editor.connection.cursor() as cursor:
        for table in tables:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_name = %s AND column_name = 'rejection_reason'",
                [table],
            )
            if cursor.fetchone():
                cursor.execute(
                    f'ALTER TABLE {table} ALTER COLUMN rejection_reason DROP NOT NULL;'
                )
            else:
                cursor.execute(
                    f"ALTER TABLE {table} ADD COLUMN rejection_reason text NOT NULL DEFAULT '';"
                )


def reverse_nullable(apps, schema_editor):
    """Reverse the migration - make fields NOT NULL again (if needed)"""
    # We don't want to reverse this, as it would break resource creation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_corpus_is_approved_course_is_approved_and_more'),
    ]

    operations = [
        migrations.RunPython(make_rejection_reason_nullable, reverse_nullable),
    ]
