# Generated by Django 5.1.7 on 2026-02-25 18:19

from django.db import migrations


def make_rejection_reason_nullable(apps, schema_editor):
    """
    Make rejection_reason field nullable in all resource tables.
    This field exists in the database but was not properly defined in the model.
    """
    with schema_editor.connection.cursor() as cursor:
        # Make rejection_reason nullable for all resource tables
        cursor.execute("""
            ALTER TABLE resources_corpus 
            ALTER COLUMN rejection_reason DROP NOT NULL;
        """)
        cursor.execute("""
            ALTER TABLE resources_course 
            ALTER COLUMN rejection_reason DROP NOT NULL;
        """)
        cursor.execute("""
            ALTER TABLE resources_nlptool 
            ALTER COLUMN rejection_reason DROP NOT NULL;
        """)
        cursor.execute("""
            ALTER TABLE resources_document 
            ALTER COLUMN rejection_reason DROP NOT NULL;
        """)


def reverse_nullable(apps, schema_editor):
    """Reverse the migration - make fields NOT NULL again (if needed)"""
    # We don't want to reverse this, as it would break resource creation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_corpus_is_approved_course_is_approved_and_more'),
    ]

    operations = [
        migrations.RunPython(make_rejection_reason_nullable, reverse_nullable),
    ]
