# Generated by Django 5.1.7 on 2026-03-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_corpus_rejection_reason_course_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='course',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
        ),
    ]
