# Generated by Django 5.1.7 on 2026-03-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_corpus_rejection_reason_course_rejection_reason_and_more'),
    ]

    # NOTE:
    # Migration 0008 already creates/normalizes rejection_reason on these tables.
    # Keep 0009 as a no-op to avoid duplicate-column failures on startup.
    operations = []
