# Generated by Django 5.1.7 on 2026-03-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_corpus_rejection_reason_course_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nlptool",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Tool icon or thumbnail image",
                null=True,
                upload_to="tools/thumbnails/",
            ),
        ),
    ]
