# Generated by Django 5.1.7 on 2026-03-19 00:47

from django.db import migrations, models


def add_thumbnail_if_missing(apps, schema_editor):
    NLPTool = apps.get_model("resources", "NLPTool")
    table_name = NLPTool._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if "thumbnail" in existing_columns:
        return

    field = models.ImageField(
        blank=True,
        help_text="Tool icon or thumbnail image",
        null=True,
        upload_to="tools/thumbnails/",
    )
    field.set_attributes_from_name("thumbnail")
    schema_editor.add_field(NLPTool, field)


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_corpus_rejection_reason_course_rejection_reason_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_thumbnail_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="nlptool",
                    name="thumbnail",
                    field=models.ImageField(
                        blank=True,
                        help_text="Tool icon or thumbnail image",
                        null=True,
                        upload_to="tools/thumbnails/",
                    ),
                ),
            ],
        ),
    ]
