# Generated by Django 5.1.7 on 2026-03-19 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_drop_legacy_corpus_file_format_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Corpus', 'verbose_name_plural': 'Corpora'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_format',
        ),
        # Skip adding rejection_reason fields - they already exist in older migrations
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['field'], name='resources_c_field_88bfb4_idx'),
        ),
        migrations.AlterModelTable(
            name='corpus',
            table=None,
        ),
    ]
