# Generated by Django 5.1.7 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0014_merge_0012_0013_resources_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="nlptool",
            name="github_url",
            field=models.URLField(
                blank=True,
                db_index=True,
                help_text="Primary GitHub repository URL for this tool",
                null=True,
                verbose_name="GitHub URL",
            ),
        ),
    ]
