# Generated by Django 5.1.7 on 2026-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0015_nlptool_github_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="certificate_available",
            field=models.BooleanField(
                default=False, verbose_name="Certificate Available"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Duration"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="enrollment_url",
            field=models.URLField(blank=True, null=True, verbose_name="Enrollment URL"),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="Is Free"),
        ),
        migrations.AddField(
            model_name="course",
            name="platform",
            field=models.CharField(
                choices=[
                    ("coursera", "Coursera"),
                    ("youtube", "YouTube"),
                    ("mit", "MIT"),
                    ("edx", "edX"),
                    ("university", "University"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
                verbose_name="Platform",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="source_name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Source Name"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="source_url",
            field=models.URLField(blank=True, null=True, verbose_name="Source URL"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start Date"),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="author_organization",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Author Organization",
            ),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="demo_url",
            field=models.URLField(blank=True, null=True, verbose_name="Demo URL"),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="installation_instructions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Installation Instructions"
            ),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="license",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="License"
            ),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="paper_url",
            field=models.URLField(blank=True, null=True, verbose_name="Paper URL"),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="source_name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Source Name"
            ),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="source_url",
            field=models.URLField(blank=True, null=True, verbose_name="Source URL"),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="stars_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Stars Count"
            ),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="use_cases",
            field=models.JSONField(blank=True, null=True, verbose_name="Use Cases"),
        ),
        migrations.AlterField(
            model_name="nlptool",
            name="last_updated",
            field=models.DateField(blank=True, null=True, verbose_name="Last Updated"),
        ),
    ]
