# Generated by Django 5.1.15 on 2026-03-26 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_domain_model_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Corpus', 'verbose_name_plural': 'Corpora'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_format',
        ),
        migrations.AddField(
            model_name='corpus',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='course',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['field'], name='resources_c_field_88bfb4_idx'),
        ),
        migrations.AlterModelTable(
            name='corpus',
            table=None,
        ),
    ]
