# Generated by Django 5.1.15 on 2026-03-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_domain_model_indexes'),
    ]

    operations = [
    ]
