# Generated by Django 5.1.15 on 2026-03-26 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_domain_model_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Corpus', 'verbose_name_plural': 'Corpora'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE resources_document DROP COLUMN IF EXISTS file_format;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='document',
                    name='file_format',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE resources_corpus
                    ADD COLUMN IF NOT EXISTS rejection_reason text NULL DEFAULT '';
                    ALTER TABLE resources_course
                    ADD COLUMN IF NOT EXISTS rejection_reason text NULL DEFAULT '';
                    ALTER TABLE resources_document
                    ADD COLUMN IF NOT EXISTS rejection_reason text NULL DEFAULT '';
                    ALTER TABLE resources_nlptool
                    ADD COLUMN IF NOT EXISTS rejection_reason text NULL DEFAULT '';
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='corpus',
                    name='rejection_reason',
                    field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
                ),
                migrations.AddField(
                    model_name='course',
                    name='rejection_reason',
                    field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
                ),
                migrations.AddField(
                    model_name='document',
                    name='rejection_reason',
                    field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
                ),
                migrations.AddField(
                    model_name='nlptool',
                    name='rejection_reason',
                    field=models.TextField(blank=True, default='', help_text='Reason for rejection (only filled when status is rejected)', null=True, verbose_name='Rejection Reason'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS resources_c_field_88bfb4_idx ON resources_corpus (field);",
                    reverse_sql="DROP INDEX IF EXISTS resources_c_field_88bfb4_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='corpus',
                    index=models.Index(fields=['field'], name='resources_c_field_88bfb4_idx'),
                ),
            ],
        ),
        migrations.AlterModelTable(
            name='corpus',
            table=None,
        ),
    ]
