# Generated by Django 5.1.15 on 2026-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_merge_20260325_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlptool',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Tool icon or thumbnail image', null=True, upload_to='tools/thumbnails/'),
        ),
    ]
