# Generated by Django 5.1.15 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0018_alter_corpus_options_remove_document_file_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="entities",
            field=models.JSONField(blank=True, default=dict, verbose_name="Entities"),
        ),
        migrations.AddField(
            model_name="course",
            name="entities",
            field=models.JSONField(blank=True, default=dict, verbose_name="Entities"),
        ),
        migrations.AddField(
            model_name="document",
            name="entities",
            field=models.JSONField(blank=True, default=dict, verbose_name="Entities"),
        ),
        migrations.AddField(
            model_name="nlptool",
            name="entities",
            field=models.JSONField(blank=True, default=dict, verbose_name="Entities"),
        ),
    ]
