# Generated by Django 5.1.15 on 2026-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_merge_20260326_2136'),
    ]

    operations = [
    ]
