# Generated by Django 5.1.7 on 2026-03-31 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_merge'),
        ('resources', '0021_merge_resources_leafs'),
    ]

    operations = [
    ]
