# Generated by Django 5.1.15 on 2026-04-11 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_merge_0021_merge_0021_merge_resources_leafs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corpus',
            name='rejection_note',
            field=models.TextField(blank=True, default='', help_text='Additional moderator notes for rejection', verbose_name='Rejection Note'),
        ),
        migrations.AddField(
            model_name='course',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='course',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='rejection_note',
            field=models.TextField(blank=True, default='', help_text='Additional moderator notes for rejection', verbose_name='Rejection Note'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_note',
            field=models.TextField(blank=True, default='', help_text='Additional moderator notes for rejection', verbose_name='Rejection Note'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nlptool',
            name='rejection_note',
            field=models.TextField(blank=True, default='', help_text='Additional moderator notes for rejection', verbose_name='Rejection Note'),
        ),
    ]
