# Generated by Django 5.1.15 on 2026-04-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Scraped At'),
        ),
        migrations.AddField(
            model_name='document',
            name='update_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Update Counter'),
        ),
    ]
