# Generated by Django 5.1.15 on 2026-04-21 10:58
# Converted to no-op because the target columns already exist in environments
# where this branch is replayed after previous schema updates.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_law'),
    ]

    operations = []
