# Generated by Django 5.1.15 on 2026-04-18 17:37
# Converted to no-op because equivalent schema changes are already handled in
# 0025_document_scrape_tracking_fix + 0026_* on the merged branch.

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_law'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
