# Generated by Django 5.1.15 on 2026-04-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_nlptool_thumbnail'),
        ('resources', '0025_add_document_scrape_fields'),
        ('resources', '0026_alter_corpus_deleted_by_alter_course_deleted_by_and_more'),
    ]

    operations = [
    ]
