# Generated by Django 5.1.15 on 2026-04-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_merge_20260424_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='access_link',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Access Link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='access_link',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Access Link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enrollment URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='document',
            name='access_link',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Access Link'),
        ),
        migrations.AlterField(
            model_name='law',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='nlptool',
            name='access_link',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Access Link'),
        ),
        migrations.AlterField(
            model_name='nlptool',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Source URL'),
        ),
    ]
