# Generated by ChatGPT to resolve migration conflict between 0028 leaf nodes.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0028_increase_url_max_length"),
        ("resources", "0028_merge_20260424_2102"),
    ]

    operations = []
