# Generated by Codex on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pendingproject_project_approval_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE projects_project
                        ADD COLUMN IF NOT EXISTS rejection_reason text;
                        ALTER TABLE projects_project
                        ALTER COLUMN rejection_reason DROP NOT NULL;
                        ALTER TABLE projects_project
                        ALTER COLUMN rejection_reason SET DEFAULT '';
                        UPDATE projects_project
                        SET rejection_reason = ''
                        WHERE rejection_reason IS NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE projects_project
                        ALTER COLUMN rejection_reason DROP DEFAULT;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='rejection_reason',
                    field=models.TextField(
                        blank=True,
                        default='',
                        help_text='Reason for rejection (only filled when status is rejected)',
                        null=True,
                        verbose_name='Rejection Reason',
                    ),
                ),
            ],
        ),
    ]
