# Generated by Django 5.1.7 on 2026-03-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_merge_0006_0007'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectchatmessage',
            new_name='projects_pr_room_id_4f9ac9_idx',
            old_name='projects_pr_room_id_619130_idx',
        ),
        migrations.RenameIndex(
            model_name='projectchatmessage',
            new_name='projects_pr_sender__bb94dd_idx',
            old_name='projects_pr_sender__6902fa_idx',
        ),
        migrations.RenameIndex(
            model_name='projectchatmessage',
            new_name='projects_pr_room_id_ec24f1_idx',
            old_name='projects_pr_room_id_54be6c_idx',
        ),
        migrations.RenameIndex(
            model_name='projectinvitation',
            new_name='projects_pr_project_ce99ba_idx',
            old_name='projects_pro_project_0f7178_idx',
        ),
        migrations.RenameIndex(
            model_name='projectinvitation',
            new_name='projects_pr_invited_386011_idx',
            old_name='projects_pro_invited_4f8aaf_idx',
        ),
    ]
