"""Split scraping views package exports."""

from scraping.views.analytics_views import (
    _build_duplicate_preview,
    _build_recent_runs_rows,
    _build_skip_reason_payload,
    _build_source_health_rows,
    _map_item_for_duplicate_check,
    analytics,
    duplicates_preview,
    recent_runs,
    skip_reason_analytics,
    source_health_summary,
    trends,
)
from scraping.views.dashboard_views import (
    _infer_source_tier,
    _media_stats,
    _model_for_category,
    dashboard,
)
from scraping.views.metrics_views import metrics_view
from scraping.views.scraper_control_views import (
    _run_source_test_job,
    add_custom_source,
    delete_custom_source,
    list_custom_sources,
    rerun_scraping_run,
    run_custom_source,
    run_scraper,
    run_scraper_status,
    task_status,
    test_source,
    test_source_status,
)
from scraping.views_root import (
    _client_ip,
    _enforce_rate_limit,
    _log_scraping_action,
    _require_json_content_type,
    _require_staff,
    is_admin,
    rate_limit,
)

__all__ = [
    "rate_limit",
    "_enforce_rate_limit",
    "_client_ip",
    "_log_scraping_action",
    "_require_staff",
    "_require_json_content_type",
    "is_admin",
    "dashboard",
    "_media_stats",
    "_infer_source_tier",
    "_model_for_category",
    "run_scraper",
    "run_scraper_status",
    "run_custom_source",
    "rerun_scraping_run",
    "test_source",
    "test_source_status",
    "_run_source_test_job",
    "add_custom_source",
    "delete_custom_source",
    "list_custom_sources",
    "task_status",
    "analytics",
    "trends",
    "skip_reason_analytics",
    "source_health_summary",
    "recent_runs",
    "duplicates_preview",
    "_build_skip_reason_payload",
    "_build_source_health_rows",
    "_build_recent_runs_rows",
    "_build_duplicate_preview",
    "_map_item_for_duplicate_check",
    "metrics_view",
]
